# Generated by Django 4.1.2 on 2022-10-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_first_name', models.CharField(max_length=256)),
                ('client_last_name', models.CharField(max_length=256)),
                ('client_commission', models.DecimalField(decimal_places=2, max_digits=8)),
                ('client_time_spent', models.DurationField()),
            ],
        ),
    ]
