# Generated by Django 4.1.2 on 2022-10-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_rate', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=1024)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=8)),
                ('time_spent', models.DurationField()),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_commission',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_time_spent',
        ),
    ]
