# Generated by Django 4.1.2 on 2022-10-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_agent_trip_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='first_name',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='last_name',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
