# Generated by Django 4.1.3 on 2022-11-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'activities'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='agents',
            field=models.ManyToManyField(null=True, related_name='activities', to='clients.agent'),
        ),
    ]
