# Generated by Django 4.1.3 on 2022-11-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_activity_agents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='agents',
        ),
        migrations.AddField(
            model_name='agent',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='agents', to='clients.activity'),
        ),
    ]
