# Generated by Django 4.1.3 on 2022-11-19 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_activitytype_remove_activity_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='type',
            new_name='act_type',
        ),
    ]
